# -*- coding: utf-8 -*-
"""Lab1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MxF0sQA_rLHZsCvcoPYWnNVL4hfaosIF
"""

# Permutation
import itertools
E = [1, 2, 3, 4]
k = 3
P = [p for p in itertools.product(E, repeat=k)]
print(P)
print("There are ", len(P), "codes.")

# Permutation
import itertools
E = {'a', 'b', 'c', 'd'}
k = 3
n = len(E)
permute_k = list(itertools.permutations(E, k))
print("%i-permutations of %s: " %(k,E))
for i in permute_k:
  print(i)
print("Size = ", "%i!/(%i-%i)! = " %(n,n,k), len(permute_k))

# Combination
import itertools
E = {'a', 'b', 'c', 'd'}
k = 3
choose_k = list(itertools.combinations(E, k))
print("%i - combinations of %s" %(k,E))
for i in choose_k:
  print(i)
print("Number of combinations = %i!/(%i!/(%i-%i)!) = %i" %(n, k, n, k, len(choose_k)))

# Urn
def cross(A, B):
  return {a + b for a in A for b in B}

urn = cross('W', '12345678') | cross('B', '123456') | cross('R', '123456789')
print(urn)
#a)
print('cau a')
import itertools
U6 = list(itertools.combinations(urn, 6))
print(U6[:10])
#b)
print('cau b')
for s in U6:
  print(s)
#c)
print('cau c')
for s in U6:
  if s[0][0] == 'R' and s[-1][0] == 'R':
    print(s)

#Exercises1:
import itertools
E = {0, 1, 2, 3, 4, 5, 6, 7, 8, 9}
k = 4
n = len(E)
num_code = list(itertools.permutations(E,k))
print("%i-permutations of %s: " %(k,E))
for i in num_code:
  print(i)
print('code_length =',len(num_code))

#Exercise2:
import itertools
A = {1, 2, 3, 4, 5}
num_3_digit = list(itertools.permutations(A, 3))
num_length = len(num_3_digit)
print('num 3 digit =',num_3_digit)
print('num length =',num_length)

#Exercise3:
import itertools
def cross(A, B):
  return {a + b for a in A for b in B}
urn = cross('W', '12345678') | cross('B', '123456') | cross('R', '123456789')
print(urn)
#a)
print('cau a')
U3 = list(itertools.combinations(urn, 3))
print(U3)
len_U3 = len(U3)
print(len_U3)
#b)
print('cau b')
for s in U3:
   if (s[0][0] != s[1][0]) and (s[0][0] != s[2][0]) and (s[1][0] != s[2][0]):
    print(s)
#c)
print('cau c')
for s in U3:
  if s[0][0] == 'W' and s[1][0] == 'R':
    print(s)

#Exercise4:
def cross (A, B):
  return {a+b for a in A for b in B}
urn = cross ('M', '1234') |cross ('P', '123') | cross ('C', '12') |cross ('L', '1')
U10 = list(itertools.permutations(urn, 10))
for s in U10:
  ten = ""
  for i in s:
    ten = ten + i[0]
    if 'M'*4 in ten and 'P'*3 in ten and 'C'*2 in ten and 'L' in ten:
      ten = ten + i[0]
print(ten)