# -*- coding: utf-8 -*-
"""Lab9.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eTZr_yuyLKbdKucXggvo6EHl1LrQbFT4
"""

#Line charts
import matplotlib.pyplot as plt
import numpy as np

samples = [0.895, 0.91, 0.919, 0.926, 0.929, 0.931]
plt.plot(samples)

import matplotlib.pyplot as plt
import numpy as np

years = [2010, 2011, 2012, 2013, 2014, 2015]
samples = [0.895, 0.91, 0.919, 0.926, 0.929, 0.931]
plt.xlabel('Year')
plt.ylabel('Yield')
plt.plot(years, samples)

import matplotlib.pyplot as plt
import numpy as np

years = range (2000, 2010, 1)
apples = [0.895, 0.91, 0.919, 0.926, 0.929, 0.931, 0.934, 0.936, 0.937, 0.9375]
oranges = [0.962, 0.941, 0.930, 0.923, 0.918, 0.908, 0.907, 0.904, 0.901, 0.898]
plt.plot(years, apples)
plt.plot(years, oranges)
plt.xlabel('Year')
plt.ylabel('Yield')
plt.show()

import matplotlib.pyplot as plt
import numpy as np

years = range (2000, 2010, 1)
apples = [0.895, 0.91, 0.919, 0.926, 0.929, 0.931, 0.934, 0.936, 0.937, 0.9375]
oranges = [0.962, 0.941, 0.930, 0.923, 0.918, 0.908, 0.907, 0.904, 0.901, 0.898]
plt.plot(years, apples)
plt.plot(years, oranges)
plt.xlabel('Year')
plt.ylabel('Yield')
plt.title("Crop Yields in Kanto")
plt.legend(['Apples', 'Oranges'])

import matplotlib.pyplot as plt
import numpy as np

years = range (2000, 2010, 1)
apples = [0.895, 0.91, 0.919, 0.926, 0.929, 0.931, 0.934, 0.936, 0.937, 0.9375]
oranges = [0.962, 0.941, 0.930, 0.923, 0.918, 0.908, 0.907, 0.904, 0.901, 0.898]
plt.plot(years, apples, marker = 'x')
plt.plot(years, oranges, marker = 'o')
plt.xlabel('Year')
plt.ylabel('Yield')
plt.show()

import matplotlib.pyplot as plt
import numpy as np

years = range (2000, 2010, 1)
apples = [0.895, 0.91, 0.919, 0.926, 0.929, 0.931, 0.934, 0.936, 0.937, 0.9375]
oranges = [0.962, 0.941, 0.930, 0.923, 0.918, 0.908, 0.907, 0.904, 0.901, 0.898]
plt.figure(figsize = (9, 3))
plt.plot(years, apples, marker = 'x')
plt.show()

#Scatter Plot
import matplotlib.pyplot as plt
import numpy as np

girls_grades = np.random.randint(100, size = 30)
boys_grades = np.random.randint(100, size = 30)
grades_range = np.random.randint(100, size = 30)
fig = plt.figure(figsize = (3, 3))
ax = fig.add_axes([0,0,1,1])
ax.scatter(grades_range, girls_grades, color = 'r')
ax.scatter(grades_range, boys_grades, color = 'b')
ax.set_xlabel('Grades Range')
ax.set_ylabel('Grades Scored')
ax. set_title('scatter plot')
plt.show()

#Bar Graphs
import matplotlib.pyplot as plt
import numpy as np

years = range(2000, 2006)
oranges = [0.4, 0.8, 0.9, 0.7, 0.6, 0.8]
plt.xlabel('Year')
plt.ylabel('Yield')
plt.bar(years, oranges)
plt.show()

import matplotlib.pyplot as plt
import numpy as np

years = range(2000, 2006)
oranges = [0.4, 0.8, 0.9, 0.7, 0.6, 0.8]
apples = [0.35, 0.6, 0.9, 0.8, 0.65, 0.8]
plt.bar(years, apples)
plt.bar(years, oranges, bottom = apples)
plt.show()

import matplotlib.pyplot as plt
import numpy as np

data = [[30, 25, 50, 20], [40, 23, 51, 17]]
X = np.arange(4)
fig = plt.figure()
ax=fig.add_axes([0,0,1,1])
ax.bar(X + 0.00, data[0], color = 'b', width = 0.25)
ax.bar(X + 0.25, data[1], color = 'g', width = 0.25)
ax.set_xticks([0.25,1.25,2.25,3.25])
ax.set_xticklabels ([2015,2016,2017,2018])
ax.legend(labels=['Oranges', 'Apples'])
plt.show()

#Histogram
from matplotlib import pyplot as plt
import numpy as np

fig, ax = plt.subplots(1,1)
a = np.array([72,87,5,73,56,73,55,54,11,20,51,5,79,31,27])
ax.hist(a, bins = [0,25,50,75,100])
ax.set_title("histogram of result")
ax.set_xticks([0,25,50,75,100])
ax.set_xlabel('marks')
ax.set_ylabel('no. of students')
plt.show()

#Exercise1
from google.colab import files
uploaded = files.upload()
import numpy as np
import pandas as pd
data = pd.read_csv("iris.csv")

#1
sepal_length = data['sepal_length']
sepal_width = data['sepal_width']
fig = plt.figure(figsize = (3, 3))
ax = fig.add_axes([0, 0, 1, 1])
ax.scatter(sepal_length, sepal_width, color='r')
ax.set_xlabel('sepal_length')
ax.set_ylabel('sepal_width')
ax.set_title('Scatter Plot')
plt.show()
print()

#2
fig, ax = plt.subplots(1, 1)
a = np.array(sepal_length)
ax.hist(a, bins = 20)
ax.set_title("Histogram of Result")
ax.set_xlabel('sepal_length')
ax.set_ylabel('No. of sepal_length')
plt.show()

#Exercise2
from google.colab import files
uploaded = files.upload()
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
data = pd.read_csv("company-sales_data.csv")

#1
month = data['month_number']
total_profit = data['total_profit']
plt.xticks(data['month_number'])
plt.xlabel('Month')
plt.ylabel('Total Profit')
plt.plot(month, total_profit)

#2
toothpaste = data['toothpaste']
month = data['month_number']
fig = plt.figure(figsize = (3, 3))
ax = fig.add_axes([0,0,1,1])
ax.scatter(month, toothpaste, color = 'r')
ax.set_xlabel('Toothpaste')
ax.set_ylabel('Month')
ax.set_title('scatter plot')
plt.show()

#3
data.plot(x = "month_number", y = ["facecream", "facewash"], kind = "bar", rot = 0, xlabel='Month', ylabel = 'No. Of Products')
plt.show()

#Exercise3
import matplotlib.pyplot as plt
import re
from collections import Counter

ftext = 'text.txt'
with open(ftext, 'r') as file:
    text = file.read()

words = re.findall(r'\w+', text.lower())

word_counts = {}
for word in words:
    if word in word_counts:
        word_counts[word] += 1
    else:
        word_counts[word] = 1

sorted_word_counts = sorted(word_counts.items(), key = lambda x: x[1], reverse = True)

top_30_words = sorted_word_counts[:30]
words, counts = zip(*top_30_words)

plt.plot(words, counts)
plt.xlabel('Words')
plt.ylabel('Frequency')
plt.title('30 Most Common Words')
plt.xticks(rotation = 90)
plt.show()