# -*- coding: utf-8 -*-
"""Lab8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19iZ4cy_ARFqMvnchuWSWdxnOj9eQgVyJ
"""

#Create a sample DataFrame
import pandas as pd
df = pd.DataFrame({'numbers': [1, 2, 3], 'colors': ['red', 'white', 'blue']})
print(df)
print()
df1 = pd.DataFrame({'numbers': [1, 2, 3], 'colors': ['red', 'white', 'blue']}, columns = ['numbers', 'colors'])
print(df1)

#Create a sample DataFrame using Numpy
import numpy as np
import pandas as pd

df = pd.DataFrame(np.random.randn(5, 3), columns = ['N1', 'N2', 'N3'])
print(df)

#Create a DataFrame from a dictionary of lists
import pandas as pd
df = pd.DataFrame ({'N1' : [1, 2, 3, 4], 'N2' : [4, 3, 2, 1]})
print(df)

#Create a DataFrame from a list of dictionaries
import pandas as pd
L = [{'Name' : 'John', 'Last Name' : 'Smith'}, {'Name' : 'Mary', 'Last Name' : 'Wood'}]
df = pd.DataFrame(L)
print(df)

#Input from text file
from google.colab import files
uploaded = files.upload()
import numpy as np
import pandas as pd

data = np.loadtxt("sample.txt", delimiter = ',')
print(data)
print()
data1 = pd.read_csv("sample.txt", delimiter = ',')
print(data1)

from google.colab import files
uploaded = files.upload()
import numpy as np
import pandas as pd

data = pd.read_csv('sample1.txt', delimiter = ',')
print(data)
print("Print column Score")
print(data.Score)

#Access data
import numpy as np
import pandas as pd

df = pd.DataFrame(np.random.randn(10, 3), columns = ['N1', 'N2', 'N3'])
print(df)
print()

print(df.head(5))
print()

print(df.tail(5))
print()

N2 = df['N2']
print(N2)
print()

N = df[['N1', 'N2']]
print(N)
print()

print(df[1:-2])

#Exercise 1
from google.colab import files
uploaded = files.upload()
import numpy as np
import pandas as pd

import pandas as pd
import numpy as np

data = pd.read_csv("iris.csv")
df = pd.DataFrame(data)

print(df.head(5))
print()

def count(data):
    count = 0
    for i in range(0, len(data) + 1):
        count += 1
    return count

def mean(data):
    n = count(data)
    sum = data.sum()
    return sum / n

def std(data):
    n = count(data)
    m = mean(data)
    square_diff = [(x - m) ** 2 for x in data]
    mean_square_diff = sum(square_diff) / n
    std = mean_square_diff ** (1 / 2)
    return std

def min(data):
    return data.min()

def max(data):
    return data.max()

s1 = df["sepal_length"]
s2 = df["sepal_width"]
s3 = df["petal_length"]
s4 = df["petal_width"]

dt = pd.DataFrame({
        "sepal_length": [count(s1), mean(s1), std(s1), min(s1), max(s1)],
        "sepal_width": [count(s2), mean(s2), std(s2), min(s2), max(s2)],
        "petal_length": [count(s3), mean(s3), std(s3), min(s3), max(s3)],
        "petal_width": [count(s4), mean(s4), std(s4), min(s4), max(s4)],})

new_row_name = ["count", "mean", "std", "min", "max"]
dt = dt.set_index(pd.Index(new_row_name))
print(dt)

from google.colab import files
uploaded = files.upload()
import numpy as np
import pandas as pd

data = pd.read_csv("population.csv")
print(data.head(5))
print()

dt = data.groupby(["Country Name", "Country Code"]).agg({"Year": ["count", "mean", "std", "min", "max"]})
print(dt)